spring:
  application:
    name: sigo-cloud-center
  profiles: node1
server:
  port: 8000
eureka:
  instance:
    hostname: node1
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://node2:8001/eureka/,http://node3:8002/eureka/