spring:
  application:
    name: sigo-cloud-center
  profiles: node2
server:
  port: 8001
eureka:
  instance:
    hostname: node2
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://node1:8000/eureka/,http://node3:8002/eureka/