spring:
  application:
    name: sigo-cloud-center
  profiles: node3
server:
  port: 8002
eureka:
  instance:
    hostname: node3
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://node1:8000/eureka/,http://node2:8001/eureka/
