## 集群方式放开注释
#spring:
#  profiles:
#    active: node1

## 单例放开注释
eureka:
  client:
    #是否需要检索服务
    fetch-registry: false
    #是否向自己注册
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
  server:
    #设为false，关闭自我保护
    enableSelfPreservation: false
    #检测间隔（单位毫秒，默认是1分钟）
    evictionIntervalTimerInMs: 4000
server:
  port: 8000
spring:
  application:
    name: sigo-cloud-center

#启动集群方式
#java -jar sigo-cloud-center-0.0.1-SNAPSHOT.jar --spring.profiles.active=node1
#java -jar sigo-cloud-center-0.0.1-SNAPSHOT.jar --spring.profiles.active=node2
#java -jar sigo-cloud-center-0.0.1-SNAPSHOT.jar --spring.profiles.active=node3